name: Check Tekton Pipeline Status

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  check-status:
    runs-on: ubuntu-latest
    steps:
      - name: Install kubectl
        run: |
          sudo apt-get update
          sudo apt-get install -y kubectl

      - name: Check Tekton Pipeline Status
        run: |
          STATUS=$(curl -s https://71f2-103-211-18-168.ngrok-free.app/ | jq -r '.status.conditions[0].reason')
          echo "Pipeline Status: $STATUS"
          if [[ "$STATUS" == "Succeeded" ]]; then
            curl -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                 -H "Accept: application/vnd.github.v3+json" \
                 https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.sha }} \
                 -d '{"state": "success", "context": "Tekton Pipeline", "description": "Pipeline completed successfully!"}'
          else
            curl -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                 -H "Accept: application/vnd.github.v3+json" \
                 https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.sha }} \
                 -d '{"state": "failure", "context": "Tekton Pipeline", "description": "Pipeline failed!"}'
          fi
